#!/bin/bash

DIARY_YEAR=$(date +%Y)
DIARY_MONTH=$(date +%m)
DIARY_DAY=$(date +%d)

DIARY_DIR=${HOME}/diary/${DIARY_YEAR}/${DIARY_MONTH}
DIARY_FILE=${DIARY_DIR}/${DIARY_DAY}.md


function diary_head()
{
    printf "# %s" "$(date "+%A, %d %B %Y")"
}


function diary_subh()
{
    case ${1} in 
        1) local str="0900 - 1030" ;;
        2) local str="1100 - 1230" ;;
        3) local str="1330 - 1500" ;;
        4) local str="1530 - 1700" ;;
    esac

    printf "## %s" "$str"
}


function diary_append()
{
    printf "%s\n" "$@" >> ${DIARY_FILE}
}


function diary_feed()
{
    diary_append ""
}


function diary_check()
{
    [[ ! -d ${DIARY_DIR} ]] && mkdir -p ${DIARY_DIR}
    [[ ! -f ${DIARY_FILE} ]] \
        && diary_append "$(diary_head)" && diary_feed && diary_feed \
        && diary_append "$(diary_subh 1)" && diary_feed \
        && diary_append "$(diary_subh 2)" && diary_feed \
        && diary_append "$(diary_subh 3)" && diary_feed \
        && diary_append "$(diary_subh 4)" && diary_feed
}


function diary_print()
{
    cat ${DIARY_FILE}
}


function diary_edit()
{
    ${EDITOR:-vim} ${DIARY_FILE}
}


function diary_update()
{
    sed -i "/^$(diary_subh ${1})$/a\n - ${2}" "${DIARY_FILE}"
}


diary_help()
{
    cat <<EOF
========================================
  Usage: diary [OPTION|-- MESSAGE]
----------------------------------------
  Manage your daily diary.
  Stored in ~/diary/YYYY/MM/DD.md

  Options:
    -e      Edit today's diary file.
    -h      Display this help message.
    -N      Record to timeblock #N.
========================================
EOF
}



function diary_main()
{
    diary_check

    [[ $# -eq 0 ]] && diary_print && exit 0
    [[ "$1" == "-h" ]] && diary_help && exit 0
    [[ "$1" == "-e" ]] && diary_edit && exit 0
    [[ "$1" =~ ^-[1-4]$ ]] && diary_update "${1#-}" "${*:2}" && exit 0

    printf "%s not a recognised diary option\n" "$1"

    exit 1
}

diary_main "$@"
