#!/bin/bash

TODO_FILE="$HOME/.todo"

function todo_stamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

function todo_list() {
    cat -n $TODO_FILE
}

function todo_undone() {
    sed -n "/\[ \]/p" $TODO_FILE | sort --k=1 --t=$(printf "\t")
}

function todo_done() {
    sed -n "/\[X\]/p" $TODO_FILE | sort --k=2 --t=$(printf "\t")
}

function todo_print() {
    local lines=$(sed 's/^.*\t//' <<< "$1")
    local num="$2"

    [[ -n "$num" ]] && lines=$(head -n $num <<< "$lines")
    nl <<< "$lines"
}

function todo_edit() {
    ${EDITOR:-vi} $TODO_FILE
}

function todo_write() {
    printf "$(todo_stamp)\t--\t[ ] $@\n" >> $TODO_FILE
}

function todo_do() {
    local mark="$1"
    [[ -z "$mark" ]] && printf "No item number given\n" && exit 1

    local line=$(sed -n "$mark p" <<< "$(todo_undone)")
    [[ -z "$line" ]] && printf "Invalid item number: $mark\n" && exit 1

    local num=$(awk -F"\t" -v line="$line" '$0 == line {print NR}' "$TODO_FILE")
    sed -i "${num}s/--\t\[ \]/$(todo_stamp)\t\[X\]/" $TODO_FILE
}

function todo_main() {
    if [[ $# -eq 0 ]]; then
        todo_print "$(todo_undone)"
        exit 0
    fi

    [[ "$1" =~ ^-.[0-9]+$ ]] && local num="${1:2}"
    [[ -z "$num" ]] && num="$2" 
    [[ ! "$num" =~ ^[0-9]*$ ]] && printf "Invalid number: $num\n" && exit 1

    if [[ "$1" == "-E" || "$1" == "--edit" ]]; then
        todo_edit
    elif [[ "$1" =~ ^-[0-9]+$ ]]; then
        todo_print "$(todo_undone)" "${1:1}" | tail -n 1
    elif [[ "$1" =~ ^-U[0-9]*$ ]]; then
        todo_print "$(todo_undone)" "$num"
    elif [[ "$1" =~ ^-D[0-9]*$ ]]; then
        todo_print "$(todo_done)" "$num"
    elif [[ "$1" =~ ^-A[0-9]*$ ]]; then
        cat <(todo_print "$(todo_undone)" "$num") <(todo_print "$(todo_done)" "$num")
    elif [[ "$1" =~ ^-d[0-9]*$ ]]; then
        todo_do "$num"
    else
        todo_write "$@"
    fi

    exit 0
}

todo_main "$@"
