#!/bin/bash

TODO_FILE="$HOME/.todo"

function todo_stamp() {
    date +"%Y-%m-%d %H:%M:%S"
}

function todo_list() {
    cat -n $TODO_FILE
}

function todo_undone() {
    sed -n "/\[ \]/p" $TODO_FILE | sort --k=1 --t=$(printf "\t")
}

function todo_done() {
    sed -n "/\[X\]/p" $TODO_FILE | sort --k=2 --t=$(printf "\t")
}

function todo_print() {
    local lines=$(sed 's/^.*\t//' <<< "$1")
    local num="$2"

    [[ -n "$num" ]] && lines=$(head -n $num <<< "$lines")
    nl <<< "$lines"
}

function todo_edit() {
    ${EDITOR:-vi} $TODO_FILE
}

function todo_write() {
    printf "$(todo_stamp)\t--\t[] $@\n" >> $TODO_FILE
}

function todo_main() {
    if [[ $# -eq 0 ]]; then
        todo_list
        exit 0
    fi

    if [[ "$1" == "-E" || "$1" == "--edit" ]]; then
        todo_edit
        exit 0
    fi

    todo_write "$@"

    exit 0
}

todo_main "$@"
