#!/bin/sh
#
# Change master volume using pactl
#
# volume [UP|DN|TA|TM]
#

STEP=5
arg="$1"

if [[ "$arg" == "UP" ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ "+%$STEP"
elif [[ "$arg" == "DN" ]]; then
    pactl set-sink-volume @DEFAULT_SINK@ "-%$STEP"
elif [[ "$arg" == "TA" ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
elif [[ "$arg" == "TM" ]]; then
    pactl set-source-mute @DEFAULT_SOURCE@ toggle
else
    printf "volume : Unrecognised command %s\n" "$1"
    printf "volume : usage \'volume [UP|DN|TA|TM]\'\n"
fi
